### ISSUE TITLE
False "No internet connection" message

### ISSUE THREAD

**Issue by haary** [nucleus-ffm/foss_warn#41]
FOSS Warn 0.2.9
Pixel 4a
GrapheneOS

I am getting false messages about "no internet connection" although internet works perfectly.
Battery optimitation is switched off for the app.

![Screenshot_20220402-092739](https://user-images.githubusercontent.com/4052999/161372325-4809a01e-c1d7-41e7-8098-622826cfac99.png)

**Comment by Tealk** [comment]
+1

**Comment by nucleus-ffm** [comment]
In 0.4.1 there was a small logic error when there are no warnings. This should be fixed with 0.4.2

**Comment by chris-asdf** [comment]
Hi,

I just upgraded to version 0.4.2 but the error is still displayed.

Interstingly if the option to show all warnings is enabled, in the 'Alle Warnungen' pane first the error is displayed, but if you reload the warnings repeatedly warnings will be shown. Without error and it seems that these the current warnings are. If you change back to the 'Meine Orte' pane the error is displayed again and no current warnings are shown.

All the best
Chris

**Comment by Tealk** [comment]
For me the message has disappeared

**Comment by chris-asdf** [comment]
Hi,

the message is still there for me (v 0.4.3 via F-Droid). The warnings are normally updated and if there is a Warning for one of my locations I also get a notification. 
So it seems the 'no Internet' message has no real reason. How is it checked anyway if there is 'internet' or not?

All the best
Chris

**Comment by chris-asdf** [comment]
Hi,

I just upgraded to 0.4.5 via f-droid and the message is gone.

Thanks,
Chris
